apiVersion: v1
kind: PersistentVolume
metadata:
  name: benchmark-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: benchmark-output-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /output
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: benchmark-metrics-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-data-pvc
  namespace: iceberg-benchmark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-output-pvc
  namespace: iceberg-benchmark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-metrics-pvc
  namespace: iceberg-benchmark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
