apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-data-pvc
  namespace: iceberg-benchmark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-results-pvc
  namespace: iceberg-benchmark
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: spark-ui
  namespace: iceberg-benchmark
  labels:
    app: iceberg-benchmark
spec:
  type: NodePort
  ports:
    - port: 4040
      targetPort: 4040
      nodePort: 30040
      name: spark-ui
  selector:
    app: iceberg-benchmark
    component: driver
---
apiVersion: v1
kind: Service
metadata:
  name: benchmark-service
  namespace: iceberg-benchmark
  labels:
    app: iceberg-benchmark
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: api
  selector:
    app: iceberg-benchmark
