# Micro benchmark configuration - Para testes rápidos
name: "micro-benchmark"
description: "Micro benchmark for quick format comparison"

# Data generation
scale_factor: 0.001  # Dados muito pequenos para teste rápido
data_dir: "/app/data/micro"

# Query configuration
queries:
  - "q1"
  - "q3"
  - "q6"

# Format comparison
formats:
  - "parquet"
  - "orc"
  - "avro"

# Compression options
compressions:
  - "snappy"
  - "gzip"
  - "zstd"

# Spark configuration
spark:
  app_name: "IcebergBenchmark-Micro"
  master: "local[2]"
  config:
    "spark.sql.adaptive.enabled": "true"
    "spark.sql.adaptive.coalescePartitions.enabled": "true"
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"

# Iceberg configuration
iceberg:
  catalog: "local"
  warehouse: "/app/output/warehouse-micro"
  
# Output configuration
output:
  base_dir: "/app/output/micro"
  metrics_dir: "/app/metrics/micro"
  include_plans: true
  include_metrics: true
